[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = '''has ('vim')'''
hook_add = '''
    let g:neocomplete#enable_at_startup = 1
    autocmd FileType python setlocal omnifunc=jedi#completions
    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    let g:neocomplete#force_omni_input_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
'''

[[plugins]]
repo ='ervandew/supertab'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagber', 'vim-fugitive']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_section_y = 'BN: %{bufnr("%")}'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
    let g:airline#extensions#branch#enabled = 0
    let g:airline#extensions#readonly#enabled = 0
    let g:airline_section_b =
        \ '%{airline#extensions#branch#get_head()}' .
        \ '%{""!=airline#extensions#branch#get_head()?("  " . g:airline_left_alt_sep . " "):""}' .
        \ '%t%( %M%)'
    let g:airline_section_c = ''
'''

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#depends = 'vim-airline'
#hook_add = '''
#    let g:airline_theme='bubblegum'
#'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# [[plugins]]
# repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
 
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'majutsushi/tagbar'

#[[plugins]]
#repo = 'edkolev/tmuxline.vim'
#hook_add = '''
#    let g:tmuxline_powerline_separators = 0
#    let g:tmuxline_preset = {
#      \'a'    : '#S',
#      \'c'    : ['#(whoami)', '#(uptime | cut -d " " -f 1,2,3)'],
#      \'win'  : '#I #W',
#      \'cwin' : '#I #W',
#      \'x'    : '%a',
#      \'y'    : '#W %R',
#      \'z'    : '#H'}
#'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term = 239
'''

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
    let g:syntastic_check_on_open=1
    let g:syntastic_check_on_wq=0
    let g:syntastic_enable_signs=1
    let g:syntastic_always_populate_loc_list=0
    let g:syntastic_python_checkers = ["flake8"]
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('nvim')'''
hook_add = '''
    let g:deoplete#enable_at_startup=1
    let g:deoplete#auto_complete_delay=0
    let g:deoplete#enable_smart_case=1
    let g:deoplete#enable_auto_close_preview = 0
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/neosnippet'
#hook_add = '''
#    let g:neosnippet#enable_snipmate_compatibility = 1
#    let g:neosnippet#snippets_directory='~/.vim/bundle/vim-snippets/snippets'
#'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#[[plugins]]
#repo = 'neoclide/coc.nvim'
#build = './install.sh nightly'
#hook_add = 'source ~/.config/nvim/coc-options.vim'

#[[plugins]]
#repo = 'itchyny/lightline.vim'
