"dein Scripts
" release autogroup in MyAutoCmd
augroup MyAutoCmd
  autocmd!
augroup END

if &compatible
" Be iMproved
  set nocompatible
endif

" dein_dir
let s:dein_dir = expand('$HOME/.vim/bundle')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

" install dein if not yet.
if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

" Required:
if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)
  
  let g:rc_dir = expand('$HOME/.vim')
  let s:toml = g:rc_dir . '/dein.toml'
  let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
 
  call dein#load_toml(s:toml ,{'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy':1})

  " You can specify revision/branch/tag.

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable
filetype plugin on

inoremap { {}<LEFT>
inoremap ( ()<LEFT>
inoremap ' ''<LEFT>
inoremap " ""<LEFT>
inoremap [ []<LEFT>
inoremap < <><LEFT>

nnoremap <Esc><Esc> :nohlsearch<CR><ESC>

autocmd FileType python setlocal completeopt-=preview
autocmd BufNewFile,BufRead *.yml setlocal tabstop=2 softtabstop=2 shiftwidth=2

map <C-n> :NERDTreeToggle<CR>
map <S-p> :PyFlakeAuto<CR>

cmap w!! w !sudo tee > /dev/null %
set incsearch
set infercase
set matchpairs& matchpairs+=<:>
set number
set ruler
set hlsearch
set showcmd
set showmatch matchtime=1
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set shortmess=a
let _curfile=expand("%:r")
if _curfile == 'makefile'
    set noexpandtab
    set tabstop=8
    set shiftwidth=8
endif
set wildmode=list:longest
set nowritebackup
set nobackup
set noswapfile
set showcmd
set relativenumber
set scrolloff=5
set wrap
set textwidth=0
set t_vb=
set novisualbell
set cmdheight=2
set laststatus=2
set display=lastline
set nomodeline

" Powerline
""python3 from powerline.vim import setup as powerline_setup
""python3 powerline_setup()
""python3 del powerline_setup
""set showtabline=2
""set noshowmode

""colorscheme antares
colorscheme spring-night
""colorscheme iceberg
""colorscheme pencil 
""colorscheme nefertiti
set background=dark
""set background=light

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts
